### ISSUE TITLE
Deploy as Maven Repository

### ISSUE THREAD

**Issue by Burdzi0** [caprica/picam#5]
It would be a good idea to deploy project as single maven repository

> Add the library jar file and its dependencies to your project class-path:
>     picam--SNAPSHOT.jar
>     jna-4.2.1.jar
>     logback-classic-1.1.7.jar
>     logback-core-1.1.7.jar
>     slf4j-api-1.7.20.jar

It's too complicated (the configuration takes too much time)

**Comment by caprica** [comment]
True, of course. But this project is not ready for a formal release due to the critical show-stopper bug documented elsewhere.

**Comment by caprica** [comment]
I appreciate this is somewhat late, but version 0.1.0 was pushed to Maven Central today, it can take a couple of hours to show up.
