### ISSUE TITLE
createComponent fails

### ISSUE THREAD

**Issue by amcelroy** [caprica/picam#6]
Howdy,

I would like to use this library in a GlassFish application for a remote imaging system in our Lab. To do this, I've done the following:

- Configured Raspbian to work with the camera
- Clone the repository
- Add the Picam src files to my project
- Build a .war file
- Deploy .war file

When running the .war file, the code gets to Camera->createEncoder->createComponent and then Java throws an exception when PointerByReference is first called in createComponent in MmalUtils class.

The exception thrown is in the doAs method in Subject.java. It seems to be a permission issue or something, but I am running the .war file as sudo. Didn't know if you had seen this, still trying to solve and will update as things progress.

<img width="663" alt="screen shot 2018-02-08 at 11 08 01 am" src="https://user-images.githubusercontent.com/4490443/35987064-62ea854e-0cc0-11e8-96de-2dc1b6928663.png">

**Comment by amcelroy** [comment]
Looks to be an issue with glassfish / payara. Found this on StackOverflow:

https://stackoverflow.com/questions/47888563/run-web-application-on-glassfish-with-newer-version-of-jna-library

Closing this out as an issue, as it is not Picam.

**Comment by caprica** [comment]
Please also remember if you intend to use this library for anything serious that there is currently a critical flaw as explained on the project home page under "Known Issues".
